### ISSUE TITLE
Macro self reference/recursion

### ISSUE THREAD

**Issue by PabstMirror** [sqf-analyzer/sqf-analyzer#3]
simplified cba macro:
```
#define LOG_SYS(LEVEL,MESSAGE) diag_log text format ['[%1] (%2)', LEVEL, MESSAGE]
#define ERROR(MESSAGE) LOG_SYS('ERROR',MESSAGE)
if (isNull _display) exitWith { ERROR("no display") };
```
error: `"diag_log" is not a valid binary operator`
in-game it de-macros to `if (isNull _display) exitWith { diag_log text format ['[%1] (%2)', 'ERROR', "no display"] };`

It's related to the `'ERROR'` inside the same named macro, but that should be valid

**Comment by LordGolias** [comment]
interesting! Thank you!

I changed this recently based on the following test:

```
#define DOUBLES(var1,var2) var1##_##var2
#define A(var1) 1 + 'DOUBLES(fnc,var1)' + 1

A(a) // equivalent to `1 + 'fnc_a' + 1`
```

but maybe this is wrong? 

This is a simplified version of the also CBA macro:

```
#define PREP(var1) ['PATHTO_SYS(PREFIX,COMPONENT_F,DOUBLES(fnc,var1))', 'TRIPLES(ADDON,fnc,var1)'] call SLX_XEH_COMPILE_NEW
```
where `PATHTO_SYS` is used within single quotes.

Do you know what is the expected behavior? I.e. whether a macro inside a single quote is replaced or not

**Comment by PabstMirror** [comment]
```
#define WORD someWord
#define TEST1 systemChat 'WORD'
#define TEST2 systemChat "WORD"
#define TEST3 systemChat 'TEST3'
#define TEST4 systemChat "TEST4"

systemChat 'someWord';
systemChat "WORD";
systemChat 'TEST3';
systemChat "TEST4";
```
these all work as expected

but it's when I run
```
#[test]
fn define_test5() {
    let case = "#define ADD2(var1,var2) var1 + var2\n
    #define THING(var1) ADD2('THING',var1)\n
    {THING(test)}";

    let mut iter = tokens(case, Default::default()).unwrap();

    let r = iter
        .by_ref()
        .map(|x| x.inner.to_string())
        .collect::<Vec<_>>();
    for s in r {
        print!("{} ", s);
    }
}
```
it seems to be demacroed to 
`{ THING '' + test }`
when it should be
`{'THING' + test}`

**Comment by LordGolias** [comment]
Found the issue. It was indeed related to macro expansion during potentially recursive macro calls.

Thank you for the help!
